variable "eks_cluster_name" {
    type = string
    description = "The name of the EKS cluster that will be created."
}
variable "eks_cluster_role" {
    type = string
    description = "The name of the IAM role that will be used for the created EKS cluster."
}
variable "eks_cluster_subnets" {
    type = list(string)
    description = "List of IDs for the subnets that the created EKS cluster will span. The subnets should be in at least 2 availability zones."
}
variable "eks_service_account_role" {
    type = string
    description = "The name of the IAM role that will be used for the service account in the created EKS cluster"
}
variable "eks_node_role" {
    type = string
    default = ""
    description = "The name of the IAM role that will be used for the created EC2 nodes in the EKS cluster."
}
variable "eks_fargate_role" {
    type = string
    default = ""
    description = "The name of the IAM role that will be used for the created Fargate profile in the EKS cluster."
}

variable "eks_node_config" {
    type = object({ ami_type = string,
                    instance_type = string,
                    disk_size = number,
                    labels = map(string),
                    launch_template_name = string,
                    launch_template_version = string,
                    subnets = list(string) })
    default = { ami_type = "AL2_x86_64",
                instance_type = "t3.medium",
                disk_size = 20,
                labels = { },
                launch_template_name = "",
                launch_template_version = "",
                subnets = [ ] }
    description = "The general configuration of the worker nodes created for the EKS cluster"
}
variable "eks_on_demand_scaling_config" {
    type = object({ name = string,
                    min_size = number,
                    max_size = number,
                    desired_size = number })
    default = { name = "",
                min_size = -1,
                max_size = -1,
                desired_size = -1 }
    description = "The scaling configuration of the node group for on-demand worker nodes created for the EKS cluster"
}
variable "eks_spot_scaling_config" {
    type = object({ name = string,
                    min_size = number,
                    max_size = number,
                    desired_size = number })
    default = { name = "",
                min_size = -1,
                max_size = -1,
                desired_size = -1 }
    description = "The scaling configuration of the node group for spot worker nodes created for the EKS cluster"
}
variable "eks_fargate_config" {
    type = object({ name = string,
                    namespace = string,
                    subnets = list(string) })
    default = { name = "",
                namespace = "",
                subnets = [ ] }
    description = "The configuration for the Fargate profile created for the EKS cluster"
}

variable "eks_cluster_version" {
    type = string
    default = "1.22.6"
    description = "The Kubernetes master version for the created EKS cluster. Defaults to \"1.22.6\""
}
variable "eks_security_groups" {
    type = list(string)
    default = [ ]
    description = "List of IDs for the security groups that nodes in the created EKS cluster will be part of in addition to the default security group created by EKS."
}
variable "eks_tags" {
    type = map(string)
    default = { }
    description = "List of key / value pairs defining the tags for the created EKS cluster."
}
variable "eks_kubernetes_labels" {
    type = map(string)
    default = { }
    description = "List of key / value pairs defining the labels that will be added to Kubernetes for the created EKS cluster."
}
variable "eks_cluster_logs" {
    type = list(string)
    default = [ "api", "audit", "authenticator", "controllerManager", "scheduler" ]
    description = "List of logs generated by the created EKS cluster. Defaults to all available EKS logs: api, audit, authenticator, controllerManager and scheduler"
}
variable "eks_cluster_cidr" {
    type = string
    default = "10.100.0.0/16"
    description = "The CIDR block that the created EKS cluster will assign Kubernetes service IP addresses from. Defaults to \"10.100.0.0/16\""
}
variable "eks_secure_cluster" {
    type = bool
    default = true
    description = "Flag indicating whether the the default security group created by EKS should be secured in accordance with best practices. Defaults to \"true\""
}

variable "eks_node_ssh_key" {
    type = string
    default = ""
    description = "EC2 Key Pair name that provides access for SSH communication with the worker nodes in the EKS Node Group. If you specify this configuration, but do not specify \"eks_node_ssh_security_groups\" when you create an EKS Node Group, port 22 on the worker nodes is opened to the Internet (0.0.0.0/0)."
}
variable "eks_node_ssh_security_groups" {
    type = list(string)
    default = [ ]
    description = "List of EC2 Security Group IDs to allow SSH access (port 22) from on the worker nodes. Default to an empty list which will open SSH access to the worker nodes to the Internet (0.0.0.0/0)"
}
variable "eks_add_ons" {
    type = list(string)
    default = [ "coredns", "kube-proxy", "vpc-cni" ]
    description = "List of EKS add-ons that will be installed in the created cluster, see https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html for details. Defaults to: coredns, kube-proxy and vpc-cni"
}